# Generated by Django 4.2.7 on 2023-11-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_qnapost_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnapost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qnapost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
