# Generated by Django 4.2.7 on 2023-11-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_qnapost_updated_at_alter_qnapost_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnapost',
            old_name='content',
            new_name='Question',
        ),
    ]
