# Generated by Django 4.2.7 on 2023-12-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notice_image',
            field=models.ImageField(blank=True, upload_to='notice/images/%y/%m/%d/'),
        ),
    ]
