# Generated by Django 3.1.1 on 2023-12-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notice_image',
            field=models.ImageField(blank=True, upload_to='notice/images/%y/%m/%d/'),
        ),
    ]
