# Generated by Django 3.1.1 on 2023-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20231203_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notice_image',
            field=models.ImageField(blank=True, default='default_image.png', upload_to='notice/images/%y/%m/%d/'),
        ),
    ]
