# Generated by Django 3.1.1 on 2023-11-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, default='', max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ColorCategories',
            },
        ),
        migrations.CreateModel(
            name='NumberCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'NumberCategories',
            },
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'SizeCategories',
            },
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, default='', max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'TypeCategories',
            },
        ),
        migrations.CreateModel(
            name='ProductsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='products/images/%Y/%m/%d/')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colorcategory')),
                ('type', models.ManyToManyField(blank=True, to='products.TypeCategory')),
            ],
        ),
    ]
