# Generated by Django 4.2.5 on 2023-11-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsTag',
            new_name='CategoryTag',
        ),
    ]
