# Generated by Django 4.2.7 on 2023-11-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productstag_categorytag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspost',
            old_name='category_tag',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productspost',
            old_name='color_tag',
            new_name='color',
        ),
    ]
