# Generated by Django 4.2.7 on 2023-11-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productspost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspost',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/images/%Y/%m/%d/'),
        ),
    ]
