# Generated by Django 4.2.7 on 2023-11-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tag_productspost_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ProductsTag',
        ),
    ]
